config/routes.rb
Rails.application.routes.draw do
  root to:  "homes#top"
  get 'home/about' => "homes#about", as: 'about'
  # get 'homes/top'
  # root to: 'users#top'
   devise_for :users
  # get 'books/new'
  # post 'book' => 'books#create'

# resources :books_image, only: [:new, :create, :index, :show]
resources :users
resources :books
delete 'books/:id' => 'books#destroy', as: 'destroy'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :image
 validates :title, presence: true
  validates :body, presence: true
  validates :body,:title, presence: true
  validates :body, length: { in: 1..200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :books, dependent: :destroy
  has_one_attached :profile_image
  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }
   def get_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top,:about]
    before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def  top
  end

  def new
   @book = Book.new
  # @book_image = Book_Image.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def update
    @books = Book.all
     @book = Book.find(params[:id])
     if @book.update(book_params)
       redirect_to book_path(@book), notice: 'You have updated book successfully'
     else
       flash.now[:alert] = "error メッセージを入力してください"
       render :index
     end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = @book.user

  end

  def edit
    @book = Book.find(params[:id])
      @user = @book.user
      unless @user == current_user
     redirect_to(books_path)
      end
  end


  def create
     @books = Book.all
     @book = Book.new(book_params)
     @book.user_id = current_user.id
     if @book.save
       redirect_to book_path(@book.id), notice: 'You have created book successfully.'
     else
       render :index
     end
  end



  def destroy
  book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :profile_image, :name, :introduction)

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about
  end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
    before_action :book_user, only: [:edit, :update]
    def top

    end

    def edit
      @users = User.all
      @user = User.find(params[:id])



    end

    def index
      @user = current_user
      @users = User.all
      @book = Book.new
    end

    def update
      @users = User.all
      @user = User.find(params[:id])
     if @user.update(user_params)
       redirect_to user_path(@user), notice: 'You have updated user successfully.'
     else
       render :edit
     end
    end

   def show
      @user = User.find(params[:id])
      @books = @user.books
      @book = Book.new

    # if @user.update(user_params)
    #   redirect_to group_messages_path(@user), notice: 'You have created book successfully.'
    # else
    #   flash.now[:alert] = 'error'
    #   render :index
    # end
   end

  def create
     @user = @user.save(user_params)
     if @user.save
       redirect_to user_path(@user), notice: 'Signed in successfully'
     else
       flash.now[:alert] = "error メッセージを入力してください"
       render :index
     end

  end

  private

    def user_params
      params.require(:user).permit(:profile_image, :name, :introduction, :title, :body)
    end


    def book_user
     @user = User.find(params[:id])
     unless @user == current_user
     redirect_to user_path(current_user)
     end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
          <div class="container">
            <div class="row">
              <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            		<h1>Editing Book</h1>
            <%= form_with model: @book do |f| %>
                  <div class="form-group">
                    <label for="book_title">Title</label>
                  </div>
                  <div class="form-group">
                      <%= f.text_field :title %>
                  </div>
                  <div class="form-group">
                      <label for="user_name">Opinion</label>
                  </div>
                  <div class="form-group">
                      <%= f.text_area :body %>
                  </div>
                  <div class="form-group">
                    <%= f.submit nil, :class => "btn btn-success" %>
                  </div>
          <% end %>

                <%= link_to "Show", book_path(@book) %> |
                <%= link_to "Back", books_path %>

                </div>
            </div>
          </div>

app/views/books/index.html.erb
<div class="flash-notifications">
  <% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: key) %>
  <% end %>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>
<p id="notice"></p>
<div class="container px-5 px-sm-0">

  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= image_tag current_user.get_image(100,100) %>

         <table class="table table-hover table-inverse">
           <tbody>
             <tr></tr>
              <tr>
    	        <th>name</th>
    	        <th><%= current_user.name %></th>
              </tr>
              <tr>
    	        <th>introduction</th>
    	        <th><%= current_user.introduction %></th>
              </tr>
            </tbody>
          </table>
         <div class= "row">
           <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary  btn-block" do%>
           <i class="fas fa-user-cog"></i>
           <% end %>
         </div>
<%= form_with model: @book, url:'/books' do |f| %>

  <h2 class="mt-3">New book</h2>
    <div class="form-group">
      <label for="book_title">Title</label>
    </div>
      <div class="form-group">
        <%= f.text_field :title %>
    </div>
     <div class="form-group">
         <label for="book_opinion">Opinion</label>
         </div>
         <div class="form-group">
          <%= f.text_area :body %>
    </div>
        <div class="form-group">
          <%= f.submit nil, :class => 'btn btn-success' %>
        </div>
 <% end %>
    </div>
     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
                <th></th>
              <div class="form-group">
                <th>Title</th>
              </div>
              <div class="form-group">
                <th>Opinion</th>
              </div>
              <div class="form-group">
                <th colspan="3"></th>
              </div>
            </tr>
          </thead>
              <tbody>
               <% @books.each do |book| %>

              <tr>
                <td>
               <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_image(80,80) %>
                <% end %>
                </td>
                  <td>
                <%= link_to book.title, book_path(book) %>
                  </td>
                    <td>
                    <%= book.body %>
                    </td>
              </tr>
               <% end %>
                </tbody>
               </table>
    </div>
</div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">

  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= image_tag current_user.get_image(100,100) %>

         <table class="table table-hover table-inverse">
           <tbody>
             <tr></tr>
              <tr>
    	        <th>name</th>
    	        <th><%= @book.user.name %></th>
              </tr>
              <tr>
    	        <th>introduction</th>
    	        <th><%= @book.user.introduction %></th>
              </tr>
            </tbody>
          </table>
         <div class= "row">
           <% if @user == current_user %>
           <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary  btn-block" do%>
            <i class="fas fa-user-cog"></i>
           <% end %>
           <% else %>
           <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary  btn-block" do%>
            <i class="fas fa-user-cog"></i>
           <% end %>
           <% end %>
         </div>
              <%= form_with model: Book.new, url: books_path, method: :post do |f| %>
                <h2 class="mt-3">New book</h2>
                  <div class="form-group">
                    <label for="book_title">Title</label>
                    </div>
                     <div class="form-group">
                      <%= f.text_field :title %>
                      </div>
                     <div class="form-group">
                       <label for="book_opinion">Opinion</label>
                     </div>
                      <div class="form-group">
                        <%= f.text_field :body %>
                     </div>
                       <div class="form-group">
                         <%= f.submit "Create Book", :class => 'btn btn-success' %>
                       </div>
              <% end %>
        </div>
              <div class="col-md-8 offset-md-1">
  		          <h2>Book detail</h2>
  		           <table class="table">
  		            <tbody>
  		            <tr>



                    <td><%= image_tag @book.user.get_image(80,80) %>
                    <br>
                   <%=  link_to @book.user.name, user_path(@book.user)%>
                    </td>
                      <td>
                         <%=  link_to @book.title, book_path(@book) %>
                      </td>
                        <td>
                          <%= @book.body %>
                        </td>
                            <td>
                                <% if @book.user == current_user %>
                                <%= link_to 'Edit', edit_book_path(@book), class:"btn btn-sm btn-success" %>
                                <% end %>
                          </td>
                          <td>
                            <% if @book.user == current_user %>
                            <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger","data-confirm" => "本当に消しますか？" %>
                             <% end %>
                          </td>
                          </tr>

                   </tbody></table>
                  </div>

  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div clas = "container">
  <div class = "row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <!--<div class="col-6 d-flex justify-content-center">-->


<h1 class = "px-3 mx-auto">Welcome to<i class="fas fa-book"></i><strong>Bookers !</strong></h1>

      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

     <div class = "container">

<h1>welcome to<i class="fas fa-book"></i> Bookers !!</h1
<p>In </i><i class="fa-solid fa-book"></i><strong>Bookers,</strong>
</p>

<p>you can share and exchange your opinions , inpressions , and emotions</p>

<p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">

          <div class="row">
          <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
          <%= link_to 'Sign up',  new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
           </div>
          </div>
      </div>
     </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
     <script src="https://kit.fontawesome.com/eb6f9385ef.js" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width,initial-scale=1">
          <%= csrf_meta_tags %>
          <%= csp_meta_tag %>

          <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
        <body>
          <header>
          <% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Bookers", root_path, class: "navbar-brand" %>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
        <ul class="navbar-nav ml-auto">
          <!--<a class="nav-link text-light">-->

              <li>
                <%= link_to "/users/sign_in", class: "nav-link text-light" do %>
                <i class="fas fa-home"></i>Home
               <% end %>
              </li>
              <li>
                <%= link_to users_path, class:"nav-link text-light" do %>
                <i class="fas fa-users"></i>Users
               <% end %>
              </li>
              <li>
                 <%= link_to books_path, class:"nav-link text-light" do %>
                <i class="fas fa-book-open"></i>Books
                <% end %>
              </li>
              <li>
                 <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"></i>Log out
                <% end %>

              </li>

        </ul>
      </div>
    <% else %>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Bookers", root_path, class: "navbar-brand" %>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

      <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
        <ul class="navbar-nav ml-auto">

              <li>
                 <%= link_to "/", class:"nav-link text-light" do %>
              <i class="fas fa-home"></i>Home
                 <% end %>
              </li>
              <li>
                 <%= link_to about_path, class:"nav-link text-light" do %>
                <i class="fas fa-link"></i>About
                <% end %>
              </li>
               <%= link_to new_user_registration_path(current_user), class:"nav-link text-light" do %>
                <i class="fas fa-user-plus"></i>Sign up
                <% end %>
              </li>
              <li>
                 <%= link_to user_session_path(current_user), class:"nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i>Log in
                <% end %>
              </li>
      </div>
        </ul>
    </div>

      <% end %>
     </header>
    </nav>
<main class = "mb-auto">
  <p class="notice"><%= notice %></p>

        <%= yield %>
</main>
  <footer>
    <div class="container mt-5">
  	  <div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    		</div>
    	</div>
    </div>
  </footer>
  </body>
</html>
</table>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

<%= form_with model: @user do |f| %>
  <div class="form-group">
    <label for="user_name">Name</label>
  </div>
  <div class="form-group">
      <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <label for="user_name">Image</label>
  </div>
  <div class="form-group">
      <%= f.file_field :profile_image, accept: "image/*" %>
  </div>
  <div class="form-group">
      <label for="user_name">Introduction</label>
  </div>
  <div class="form-group">
      <%= f.text_area :introduction %>
  </div>
  <div class="form-group">
    <%= f.submit nil, :class => "btn btn-success" %>
  </div>
<% end %>

           </div>
   </div>
  </div>
    </div>

app/views/users/index.html.erb
<div class="flash-notifications">
  <% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: key) %>
  <% end %>
</div>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= link_to user_path(@user) do %>
                <%= image_tag @user.get_image(100,100) %>
                <% end %>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr></tr>
            <tr>
    	        <th>name</th>
    	        <th><%= @user.name %></th>
            </tr>
            <tr>
    	         <th>introduction</th>
    	        <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>

    <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>

        <%= form_with model: @book, url:'/books', local: true do |f| %>
        <h2>New book</h2>
            <div class="form-group">
          <label for="book_title">Title</label>
            </div>
            <div class="form-group">
              <%= f.text_field :title %>
            </div>
             <div class="form-group">
               <label for="book_opinion">Opinion</label>
             </div>
             <div class="form-group">
                <%= f.text_area :body %>
              </div>
              <div class="form-group">
                <%= f.submit nil, :class => 'btn btn-success' %>
            </div>
          <% end %>
</div>
     <div class="col-md-8 offset-md-1">
       <h2>Users</h2>
        <table class="table table-hover table-inverse">
           <thead>
            <tr>
              <th>image</th>
              <th>name</th>
               <th colspan="3"></th>
            </tr>
           </thead>
      <tbody>
              <% @users.each do |user| %>
          <tr>
            <td>
               <%= image_tag user.get_image(80,80) %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(user) %>
            </td>
          </tr>
          <% end %>
      </tbody>
      </table>
    </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info1</h2>
       <%= image_tag current_user.get_image(100,100) %>
       <table class="table">
          <tbody>
            <tr></tr>
          <tr>
        	  <th>name</th>
        	  <th><%= @user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class= "row">

           <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary  btn-block" do%>
           <i class="fas fa-user-cog"></i>
           <% end %>
         </div>


   <%= form_with model: Book.new, url: books_path, method: :post do |f| %>
    <h2 class="mt-3">New book</h2>
      <div class="form-group">
        <label for="book.title">Title</label>
      </div>
        <div class="form-group">
          <%= f.text_field :title %>
        </div>
           <div class="form-group">
             <label for="book_opinion">Opinion</label>
           </div>
             <div class="form-group">
              <%= f.text_area :body %>
              </div>
        <div class="form-group">
          <%= f.submit nil, :class => 'btn btn-success' %>
        </div>
           <% end %>


</div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <div class="form-group">
      <th></th>
      </div>
      <div class="form-group">
        <th>Title</th>
         </div>
            <div class="form-group">
                <th>Opinion</th>
              </div>
                <div class="form-group">
                  <th colspan="3"></th>
                </div>
      </tr>
  </thead>
    <tbody>
       <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= image_tag @user.get_image(80,80) %>
                <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book)%>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
      </tbody>
      </table>
    </div>
    </div>
    </div>